export WANDB_API_KEY=43a37ea993da69ae3e41784a44b8591809c865d1
# export VLLM_ATTENTION_BACKEND=XFORMERS

DATA_DIR_PATH=/zhiliang/code/Pre-train/data

RUN_ID=3B
GPU_ENV=1GPU
MODEL_ENV=Qwen2.5-Coder-3B-Instruct
# MODEL_P=/zhiliang/huggingface/hub/models--Qwen--Qwen2.5-Coder-7B-Instruct/snapshots/c03e6d358207e414f1eca0bb1891e29f1db0e242
MODEL_P=/zhiliang/huggingface/hub/models--Qwen--Qwen2.5-Coder-3B-Instruct/snapshots/488639f1ff808d1d3d0ba301aef8c11461451ec5
# MODEL_P=/zhiliang/code/Pre-train/logs/Diss_train_3B_stage3/merged_model_STAGE3_RL100_125
PROJECT_NAME=Diss_train_3B_stage1_from3b
        
LOG_PATH=logs/$PROJECT_NAME
MODEL_PATH=$MODEL_P
EXPERIMENT_NAME=$GPU_ENV-$MODEL_ENV-$RUN_ID
mkdir -p $LOG_PATH/$EXPERIMENT_NAME
set -x

python -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$DATA_DIR_PATH/train_diss_stage_1_RL_gen_is3B.parquet \
    data.val_files=$DATA_DIR_PATH/eval.parquet \
    data.train_batch_size=32 \
    data.val_batch_size=16 \
    data.max_prompt_length=8192 \
    data.max_response_length=2048 \
    actor_rollout_ref.model.path=$MODEL_PATH \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=40 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=40 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    reward_model.reward_manager=diss\
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    +trainer.logger_path=$LOG_PATH/$EXPERIMENT_NAME/rollouts.log \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.nnodes=1 \
    trainer.n_gpus_per_node=1\
    trainer.resume_mode=auto \
    trainer.val_before_train=False \
    trainer.default_local_dir=$LOG_PATH/$EXPERIMENT_NAME \
    trainer.default_hdfs_dir=null \
    trainer.resume_mode=auto \
    trainer.save_freq=20 \
    trainer.total_epochs=4 $@ 2>&1 | tee $LOG_PATH/$EXPERIMENT_NAME/grpo.log
# python -m verl.trainer.main_ppo \
#     algorithm.adv_estimator=grpo \
#     data.train_files=$DATA_DIR_PATH/diss_train_RL_stage4.parquet \
#     data.val_files=$DATA_DIR_PATH/eval.parquet \
#     data.train_batch_size=32 \
#     data.val_batch_size=16 \
#     data.max_prompt_length=8192 \
#     data.max_response_length=2048 \
#     actor_rollout_ref.model.path=$MODEL_PATH \
#     actor_rollout_ref.actor.optim.lr=1e-6 \
#     actor_rollout_ref.model.use_remove_padding=True \
#     actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
#     actor_rollout_ref.actor.ppo_mini_batch_size=16 \
#     actor_rollout_ref.actor.use_kl_loss=True \
#     actor_rollout_ref.actor.kl_loss_coef=0.001 \
#     actor_rollout_ref.actor.kl_loss_type=low_var_kl \
#     actor_rollout_ref.model.enable_gradient_checkpointing=True \
#     actor_rollout_ref.actor.fsdp_config.param_offload=False \
#     actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
#     actor_rollout_ref.rollout.log_prob_micro_batch_size=40 \
#     actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
#     actor_rollout_ref.rollout.name=vllm \
#     actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
#     actor_rollout_ref.rollout.n=8 \
#     actor_rollout_ref.rollout.temperature=0.6 \
#     actor_rollout_ref.ref.log_prob_micro_batch_size=40 \
#     actor_rollout_ref.ref.fsdp_config.param_offload=True \
#     algorithm.kl_ctrl.kl_coef=0.001 \
#     reward_model.reward_manager=diss\
#     trainer.critic_warmup=0 \
#     trainer.logger='["console","wandb"]' \
#     +trainer.logger_path=$LOG_PATH/$EXPERIMENT_NAME/rollouts.log \
#     trainer.project_name=$PROJECT_NAME \
#     trainer.experiment_name=$EXPERIMENT_NAME \
#     trainer.nnodes=1 \
#     trainer.n_gpus_per_node=1\
#     trainer.resume_mode=auto \
#     trainer.val_before_train=False \
#     trainer.default_local_dir=$LOG_PATH/$EXPERIMENT_NAME \
#     trainer.default_hdfs_dir=null \
#     trainer.resume_mode=auto \
#     trainer.save_freq=20 \
#     trainer.total_epochs=5 $@ 2>&1 | tee $LOG_PATH/$EXPERIMENT_NAME/grpo.log
